feat: add first draft of german translation.
Green-Software-Foundation/learn pull request #227
Opened 2024-05-02 17:22 UTC by franziska-warncke

Added a first draft of german translation. 

What is still needed: 
- A writer review to make sure the translation went well 
- Translation of the images

2024-05-07 10:55 UTC, russelltrow commented on i18n/de/docusaurus-plugin-content-docs/current/carbon-awareness.mdx
> +title: Carbon Awareness
Should this title be translated?

2024-05-07 10:56 UTC, russelltrow reviewed
Translations looks great and I've tested locally and it works perfectly.

2024-05-10 13:22 UTC, cdhaens requested changes
See inline

2024-05-24 14:12 UTC, russelltrow commented
Hey @franziska-warncke when might you get chance to review @cdhaens feedback please?

2024-05-24 16:11 UTC, tamarau reviewed
Hut ab :) Ein paar Kleinigkeiten meinerseits

2024-05-24 16:11 UTC, tamarau commented on i18n/de/docusaurus-plugin-content-docs/current/energy-efficiency.mdx
> +- Die Quantifizierung des Energieverbrauchs einer Anwendung ist ein Schritt in die richtige Richtung, um zu überlegen, wie eine Anwendung effizienter arbeiten kann. Das Verständnis des Energieverbrau
```suggestion
- Die Quantifizierung des Energieverbrauchs einer Anwendung ist ein Schritt in die richtige Richtung, um zu überlegen, wie eine Anwendung effizienter arbeiten kann. Das Verständnis des Energieverbrauchs Ihrer Anwendung ist jedoch nicht die einzige Geschichte. Die Hardware, auf der Ihre Software läuft, verbraucht einen Teil des Stroms für betriebliche Gemeinkosten. Dies wird im Bereich der Cloud als Stromverbrauchseffizienz (PUE - Power Usage Effectiveness) bezeichnet.
```

2024-05-24 16:11 UTC, tamarau commented on i18n/de/docusaurus-plugin-content-docs/current/energy-efficiency.mdx
> +      question: "elche Anwendung verbraucht die meiste Energie?",
```suggestion
      question: "Welche Anwendung verbraucht die meiste Energie?",
```

2024-05-24 16:11 UTC, tamarau commented on i18n/de/docusaurus-plugin-content-docs/current/energy-efficiency.mdx
> +          text: "Eine Anwendung, die 15kWh in einem Rechenzentrum mit einer PUE von 1,2 verbraucht",
```suggestion
          text: "Eine Anwendung, die 15 kWh in einem Rechenzentrum mit einer PUE von 1,2 verbraucht",
```

2024-05-24 16:11 UTC, tamarau commented on i18n/de/docusaurus-plugin-content-docs/current/energy-efficiency.mdx
> +          text: "Eine Anwendung, die 10kWh in einem Rechenzentrum mit einem PUE-Wert von 1,5 verbraucht",
```suggestion
          text: "Eine Anwendung, die 10 kWh in einem Rechenzentrum mit einem PUE-Wert von 1,5 verbraucht",
```

2024-05-24 16:11 UTC, tamarau commented on i18n/de/docusaurus-theme-classic/navbar.json
> +    "message": "ein Green Software Foundation Projekt",
```suggestion
    "message": "Ein Green Software Foundation Projekt",
```

2024-06-17 15:57 UTC, franziska-warncke commented
Sorry, I was on vacation and after that I got sick. I will look into this now. :)

2024-06-28 13:31 UTC, franziska-warncke commented on i18n/de/docusaurus-plugin-content-docs/current/carbon-efficiency.mdx
> +Die [globale Erwärmung](https://climate.nasa.gov/global-warming-vs-climate-change/) ist die seit der vorindustriellen Zeit (zwischen 1850 und 1900) beobachtete langfristige Erwärmung des Klimasystems
Mir hat ....die auf menschengemachte Aktivitäten.... besser gefallen

2024-06-28 13:34 UTC, franziska-warncke commented on i18n/de/docusaurus-plugin-content-docs/current/carbon-awareness.mdx
> +Fossile Brennstoffe sind von Natur aus abschaltbar; sie können die Energieproduktion schnell erhöhen, indem sie mehr verbrennen. Allerdings kostet Kohle Geld, so dass dies die am wenigsten bevorzugte
nice catch! 👍 Das wusste ich nicht.

2024-06-28 13:36 UTC, franziska-warncke commented on i18n/de/docusaurus-plugin-content-docs/current/carbon-awareness.mdx
> +Strom zu nutzen, wenn die Kohlenstoffintensität gering ist, ist der beste Weg, um sicherzustellen, dass Investitionen in Anlagen mit geringen Kohlenstoffemissionen fließen und nicht in Anlagen mit ho
Viel besser! Danke 🌻

2024-06-28 13:44 UTC, franziska-warncke commented on i18n/de/docusaurus-plugin-content-docs/current/carbon-awareness.mdx
> +        { text: "Eines der oben genannten", isCorrect: true },
Agree! :)

2024-06-28 15:45 UTC, franziska-warncke commented
Can you please have a look again. Thanks 🌻

2024-07-25 11:46 UTC, russelltrow commented
Hey @franziska-warncke are you happy for us to merge this and then pick-up any further changes later?

I'm aware you've been working on this for a while now.

2024-07-25 12:00 UTC, franziska-warncke commented
@russelltrow Let me add the pictures, and then it is ready for merging! :) 
I will quickly do that :)

2024-07-25 12:24 UTC, franziska-warncke commented
Done! It is now ready to be merged :)

2024-07-25 12:42 UTC, cdhaens approved these changes

2024-07-25 12:45 UTC, franziska-warncke commented on i18n/de/docusaurus-plugin-content-docs/current/carbon-awareness.mdx
> +_Tun Sie mehr, wenn der Strom sauberer ist, und tun Sie weniger, wenn der Strom schmutziger ist._
Werde ich im nächsten PR dann umsetzen :)

2024-07-25 13:16 UTC, russelltrow requested changes
Just need to fix a couple of broken images

2024-07-25 13:16 UTC, russelltrow commented on i18n/de/docusaurus-plugin-content-docs/current/energy-efficiency.mdx
> +![alt_text](./images/06_energy_proportionality_updated.png "image_tooltip")
Need to remove the "_updated" from the filename

2024-07-25 13:16 UTC, russelltrow commented on i18n/de/docusaurus-plugin-content-docs/current/introduction.md
> +![Green Software Principles, Patterns, and Practices](./images/GSF_Principles_Patterns_Practices_v2.png "Green Software Principles, Patterns, and Practices")
This image appears to be missing from the Images folder

2024-07-26 09:04 UTC, russelltrow approved these changes

2024-07-26 09:06 UTC, merged